### ISSUE TITLE
Missing files for testing the Angular JS example?

### ISSUE THREAD

**Issue by danielElopez** [osisoft/Qi-Samples#25]
When I compare this project to other Angular CLI-generated projects, I don't see a .angular-cli.json file created at the root directory (https://github.com/osisoft/Qi-Samples/tree/master/Basic/JavaScript/AngularJs), as I would expect; similarly, within the src/app folder (https://github.com/osisoft/Qi-Samples/tree/master/Basic/JavaScript/AngularJs/src/app), shouldn't there also be an app.component.css file?  Sorry if I'm misunderstanding the deployment process, but most importantly, without an .angular-cli.json file, we won't be able to ng serve the project, yes?  Thanks for the help!

**Comment by TomSeymour** [comment]
Thanks for pointing this out.  I have uploaded the file, hope this gets you going!
